// savollar.js
// Jami: 200 ta savol | 5 bo'lim | 25+ mavzu

const testSavollari = [
	// ============================================================
	// 1-BO'LIM: JAVASCRIPT XOTIRA VA FUNDAMENTAL TUSHUNCHALARI
	// ============================================================

	// --- Stack va Heap ---
	{
		id: 1,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Stack va Heap",
		savol: "JavaScript-da primitive tiplar xotirasining qaysi qismida saqlanadi?",
		variantlar: ["Heap", "Stack", "Queue", "Register"],
		togriJavob: 1,
	},
	{
		id: 2,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Stack va Heap",
		savol: "Quyidagi tiplardan qaysi biri reference (havola) tip hisoblanadi?",
		variantlar: ["number", "boolean", "string", "object"],
		togriJavob: 3,
	},
	{
		id: 3,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Stack va Heap",
		savol: "let a = { x: 1 }; let b = a; b.x = 99; console.log(a.x); — natija nima?",
		variantlar: ["1", "99", "undefined", "ReferenceError"],
		togriJavob: 1,
	},
	{
		id: 4,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Stack va Heap",
		savol: "Heap xotirasida saqlanadigan ma'lumotlar xususiyati qanday?",
		variantlar: ["Hajmi aniq va oldindan belgilangan", "Hajmi o'zgaruvchan va dinamik taqsimlanadi", "Faqat funksiya chaqiruv ketma-ketligi saqlanadi", "Faqat string lar saqlanadi"],
		togriJavob: 1,
	},
	{
		id: 5,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Stack va Heap",
		savol: "JavaScript-da Garbage Collector (axlat yig'uvchi) asosan nima qiladi?",
		variantlar: ["DOM elementlarini o'chiradi", "Endi murojaat qilinmaydigan obyektlarni xotiradan tozalaydi", "Stack overflow xatolarini tuzatadi", "setInterval ni to'xtatadi"],
		togriJavob: 1,
	},

	// --- Deep Copy va Shallow Copy ---
	{
		id: 6,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Deep Copy va Shallow Copy",
		savol: "Shallow Copy (yuzaki nusxa) nima?",
		variantlar: [
			"Obyektning barcha ichki obyektlarini ham mustaqil nusxalaydi",
			"Faqat birinchi darajali xususiyatlarni nusxalaydi, ichki obyektlarga havolani saqlaydi",
			"Faqat string xususiyatlarni nusxalaydi",
			"Hech qanday nusxa olmaydi",
		],
		togriJavob: 1,
	},
	{
		id: 7,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Deep Copy va Shallow Copy",
		savol: "const copy = { ...original }; bu usul qanday nusxa oladi?",
		variantlar: ["Deep Copy", "Shallow Copy", "Reference Copy", "Prototype Copy"],
		togriJavob: 1,
	},
	{
		id: 8,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Deep Copy va Shallow Copy",
		savol: "Deep Copy olishning to'g'ri usuli qaysi?",
		variantlar: ["const b = a;", "const b = Object.assign({}, a);", "const b = JSON.parse(JSON.stringify(a));", "const b = { ...a };"],
		togriJavob: 2,
	},
	{
		id: 9,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Deep Copy va Shallow Copy",
		savol: "JSON.parse(JSON.stringify(obj)) usulining kamchiligi nima?",
		variantlar: ["U shallow copy qiladi", "undefined, function va Date qiymatlarini to'g'ri ko'chirmaydi", "U faqat massivlar uchun ishlaydi", "U sintaksis xatosi beradi"],
		togriJavob: 1,
	},
	{
		id: 10,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Deep Copy va Shallow Copy",
		savol: "Object.assign() metodi qanday nusxa oladi?",
		variantlar: ["Deep Copy", "Shallow Copy", "Prototype Copy", "Immutable Copy"],
		togriJavob: 1,
	},

	// --- Destructuring ---
	{
		id: 11,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Destructuring",
		savol: "const { ism, yosh } = { ism: 'Ali', yosh: 20 }; — bu nima?",
		variantlar: ["Massiv destructuring", "Obyekt destructuring", "Spread operator", "Rest operator"],
		togriJavob: 1,
	},
	{
		id: 12,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Destructuring",
		savol: "const [a, , b] = [1, 2, 3]; — b ning qiymati nima?",
		variantlar: ["1", "2", "3", "undefined"],
		togriJavob: 2,
	},
	{
		id: 13,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Destructuring",
		savol: "Quyidagi kodda nima chop etiladi?\nconst { a: alias } = { a: 42 };\nconsole.log(alias);",
		variantlar: ["a", "42", "undefined", "ReferenceError"],
		togriJavob: 1,
	},
	{
		id: 14,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Destructuring",
		savol: "Funksiya parametrida destructuring qanday yoziladi?",
		variantlar: ["function f(obj) { let { x } = obj; }", "function f({ x, y }) { }", "Ikkala variant ham to'g'ri", "Destructuring faqat let/const bilan ishlaydi"],
		togriJavob: 2,
	},
	{
		id: 15,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Destructuring",
		savol: "const { x = 10 } = {}; — x ning qiymati nima?",
		variantlar: ["undefined", "null", "10", "0"],
		togriJavob: 2,
	},

	// --- RegEx ---
	{
		id: 16,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "RegEx",
		savol: "/^[a-z]+$/i — bu regex nima tekshiradi?",
		variantlar: ["Faqat raqamlardan iborat matn", "Faqat harflardan iborat matn (katta/kichik farqsiz)", "Harf va raqamlar aralashmasini", "Bo'sh matn"],
		togriJavob: 1,
	},
	{
		id: 17,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "RegEx",
		savol: "str.match(regex) metodi nima qaytaradi agar mos kelmasa?",
		variantlar: ["[]", "false", "null", "undefined"],
		togriJavob: 2,
	},
	{
		id: 18,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "RegEx",
		savol: "RegEx dagi 'g' flagi nima uchun ishlatiladi?",
		variantlar: ["Katta-kichik harfni e'tiborsiz qoldirish", "Barcha mosliklarni topish (global qidiruv)", "Ko'p qatorli qidiruvni yoqish", "Raqamlarni qidirish"],
		togriJavob: 1,
	},
	{
		id: 19,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "RegEx",
		savol: "/\\d+/ — bu pattern nima topadi?",
		variantlar: ["Bitta harf", "Bir yoki bir nechta raqam", "Bo'sh joy", "Har qanday belgi"],
		togriJavob: 1,
	},
	{
		id: 20,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "RegEx",
		savol: "str.replace(/foo/g, 'bar') — bu nima qiladi?",
		variantlar: ["Faqat birinchi 'foo' ni 'bar' ga almashtiradi", "Barcha 'foo' larni 'bar' ga almashtiradi", "Regex sintaksis xatosi beradi", "'foo' ni o'chiradi"],
		togriJavob: 1,
	},

	// --- Throw Errors ---
	{
		id: 21,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Throw Errors",
		savol: "throw new Error('Xato!') — bu nima qiladi?",
		variantlar: ["Xato xabarini consolega yozadi", "Dastur ijrosini to'xtatib, xato obyektini tashqariga uzatadi", "try...catch blokini ishga tushiradi", "Xato sinfini yaratadi"],
		togriJavob: 1,
	},
	{
		id: 22,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Throw Errors",
		savol: "try...catch...finally blokida finally qachon ishlaydi?",
		variantlar: ["Faqat xato yuz berganda", "Faqat xato bo'lmaganda", "Har doim — xato bo'lsa ham, bo'lmasa ham", "Faqat catch bloklanganda"],
		togriJavob: 2,
	},
	{
		id: 23,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Throw Errors",
		savol: "catch(e) da e.message nimani bildiradi?",
		variantlar: ["Xato turi (TypeError, RangeError va h.k.)", "Xatoning matn tavsifi", "Xato kodi (HTTP status kabi)", "Xato yuz bergan fayl nomi"],
		togriJavob: 1,
	},
	{
		id: 24,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Throw Errors",
		savol: "Qo'lda maxsus xato sinfi yaratish uchun qaysi sinfni kengaytirish kerak?",
		variantlar: ["Object", "Error", "Exception", "TypeError"],
		togriJavob: 1,
	},
	{
		id: 25,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Throw Errors",
		savol: "try bloki ichida throw ishlatilsa, kod qaysi blokka o'tadi?",
		variantlar: ["finally", "catch", "else", "return"],
		togriJavob: 1,
	},

	// ============================================================
	// 2-BO'LIM: FUNKSIYALAR VA OOP
	// ============================================================

	// --- Callback ---
	{
		id: 26,
		bolim: "Funksiyalar va OOP",
		mavzu: "Callback Funksiyalar",
		savol: "Callback funksiya nima?",
		variantlar: [
			"Faqat asinxron kodda ishlatiladigan funksiya",
			"Boshqa funksiyaga argument sifatida uzatiladigan va o'sha joyda chaqiriladigan funksiya",
			"O'zini o'zi chaqiradigan funksiya",
			"Faqat massivlar bilan ishlaydigan funksiya",
		],
		togriJavob: 1,
	},
	{
		id: 27,
		bolim: "Funksiyalar va OOP",
		mavzu: "Callback Funksiyalar",
		savol: "[1,2,3].forEach(function(el) { console.log(el); }) — bu misolda callback nima?",
		variantlar: ["forEach", "[1,2,3]", "function(el) { console.log(el); }", "console.log"],
		togriJavob: 2,
	},
	{
		id: 28,
		bolim: "Funksiyalar va OOP",
		mavzu: "Callback Funksiyalar",
		savol: "'Callback hell' degan tushuncha nimani anglatadi?",
		variantlar: ["Callbacklar sinxron ishlashi", "Ko'p darajali ichma-ich callbacklar natijasida kodni o'qib bo'lmaydigan holat", "Callbacklar xato berishi", "Callbacklarning sekin ishlashi"],
		togriJavob: 1,
	},
	{
		id: 29,
		bolim: "Funksiyalar va OOP",
		mavzu: "Callback Funksiyalar",
		savol: "setTimeout(() => console.log('Salom'), 1000); — bu callback qachon chaqiriladi?",
		variantlar: ["Darhol", "1 soniyadan so'ng", "Event loop bo'sh bo'lganda, eng kamida 1 soniyadan keyin", "Hech qachon"],
		togriJavob: 2,
	},
	{
		id: 30,
		bolim: "Funksiyalar va OOP",
		mavzu: "Callback Funksiyalar",
		savol: "Callback funksiyani sinxron ravishda chaqirish mumkinmi?",
		variantlar: [
			"Yo'q, callbacklar har doim asinxron",
			"Ha, forEach kabi metodlar callbackni sinxron chaqiradi",
			"Faqat arrow funksiyalar sinxron chaqiriladi",
			"Faqat named funksiyalar sinxron chaqiriladi",
		],
		togriJavob: 1,
	},

	// --- High Order Functions ---
	{
		id: 31,
		bolim: "Funksiyalar va OOP",
		mavzu: "High Order Functions",
		savol: "High Order Function (Yuqori tartibli funksiya) deb nimaga aytiladi?",
		variantlar: ["Faqat raqamlar bilan ishlaydigan funksiya", "Argument sifatida funksiya qabul qiladigan yoki funksiya qaytaradigan funksiya", "Rekursiv funksiya", "Katta hajmdagi funksiya"],
		togriJavob: 1,
	},
	{
		id: 32,
		bolim: "Funksiyalar va OOP",
		mavzu: "High Order Functions",
		savol: "Quyidagilardan qaysi biri High Order Function?",
		variantlar: ["Math.PI", "parseInt", "Array.prototype.map", "JSON.stringify"],
		togriJavob: 2,
	},
	{
		id: 33,
		bolim: "Funksiyalar va OOP",
		mavzu: "High Order Functions",
		savol: "function multiply(x) { return function(y) { return x * y; }; } — bu nima namunasi?",
		variantlar: ["Callback", "Rekursiya", "Currying (HOF orqali)", "IIFE"],
		togriJavob: 2,
	},
	{
		id: 34,
		bolim: "Funksiyalar va OOP",
		mavzu: "High Order Functions",
		savol: "[1,2,3,4].filter(n => n > 2) — natija nima?",
		variantlar: ["[1, 2]", "[3, 4]", "[2, 3, 4]", "[1]"],
		togriJavob: 1,
	},
	{
		id: 35,
		bolim: "Funksiyalar va OOP",
		mavzu: "High Order Functions",
		savol: "[1,2,3].reduce((acc, cur) => acc + cur, 0) — natija nima?",
		variantlar: ["0", "3", "6", "123"],
		togriJavob: 2,
	},

	// --- Closure ---
	{
		id: 36,
		bolim: "Funksiyalar va OOP",
		mavzu: "Closure",
		savol: "Closure (yopiqlik) nimani anglatadi?",
		variantlar: [
			"Funksiyaning o'zini o'zi chaqirishi",
			"Ichki funksiyaning yaratilgan muhitidagi o'zgaruvchilarni eslab qolishi",
			"Funksiyaning faqat global o'zgaruvchilarga murojaat qilishi",
			"Funksiyaning qaytarish qiymati bo'lmasligi",
		],
		togriJavob: 1,
	},
	{
		id: 37,
		bolim: "Funksiyalar va OOP",
		mavzu: "Closure",
		savol: "function counter() { let n = 0; return () => ++n; } const c = counter(); c(); c(); console.log(c()); — natija?",
		variantlar: ["1", "2", "3", "0"],
		togriJavob: 2,
	},
	{
		id: 38,
		bolim: "Funksiyalar va OOP",
		mavzu: "Closure",
		savol: "Closure-dan amaliy foydalanish misoli qaysi?",
		variantlar: ["DOM elementini tanlash", "Xususiy (private) o'zgaruvchilarni taqlid qilish", "HTML sahifani yuklash", "RegEx pattern yaratish"],
		togriJavob: 1,
	},
	{
		id: 39,
		bolim: "Funksiyalar va OOP",
		mavzu: "Closure",
		savol: "Closure o'zgaruvchining qiymatini saqlaydi yoki havolasini (reference)?",
		variantlar: [
			"Faqat qiymatni (snapshot)",
			"Havolasini — o'zgaruvchi keyinchalik o'zgarsa, closure ham yangi qiymatni ko'radi",
			"Har doim undefined saqlaydi",
			"Faqat raqam tipidagi qiymatlarni saqlaydi",
		],
		togriJavob: 1,
	},
	{
		id: 40,
		bolim: "Funksiyalar va OOP",
		mavzu: "Closure",
		savol: "IIFE (Immediately Invoked Function Expression) closure bilan qanday bog'liq?",
		variantlar: ["Bog'liqligi yo'q", "IIFE closure hosil qiladi va ichki o'zgaruvchilarni global scope dan izolyatsiya qiladi", "IIFE faqat asinxron kodi bajaradi", "IIFE DOM elementlarini yaratadi"],
		togriJavob: 1,
	},

	// --- Class ---
	{
		id: 41,
		bolim: "Funksiyalar va OOP",
		mavzu: "Class lar",
		savol: "JavaScript-da class kalit so'zi birinchi marta qaysi versiyada qo'shildi?",
		variantlar: ["ES5", "ES6 (ES2015)", "ES8", "ES10"],
		togriJavob: 1,
	},
	{
		id: 42,
		bolim: "Funksiyalar va OOP",
		mavzu: "Class lar",
		savol: "constructor() metodi qachon avtomatik chaqiriladi?",
		variantlar: ["Klassning metodlaridan biriga murojaat qilinganda", "new kalit so'zi bilan yangi ekzemplyar yaratilganda", "extends kalit so'zi ishlatilganda", "static metod chaqirilganda"],
		togriJavob: 1,
	},
	{
		id: 43,
		bolim: "Funksiyalar va OOP",
		mavzu: "Class lar",
		savol: "class B extends A — bu nima?",
		variantlar: ["Inkapsulyatsiya", "Polimorfizm", "Vorislik (Inheritance)", "Abstraksiya"],
		togriJavob: 2,
	},
	{
		id: 44,
		bolim: "Funksiyalar va OOP",
		mavzu: "Class lar",
		savol: "super() ni qachon chaqirish majburiy?",
		variantlar: ["Har doim", "Farzand klass konstruktorida this dan foydalanishdan oldin", "Faqat static metodlarda", "Hech qachon — ixtiyoriy"],
		togriJavob: 1,
	},
	{
		id: 45,
		bolim: "Funksiyalar va OOP",
		mavzu: "Class lar",
		savol: "static metod qanday chaqiriladi?",
		variantlar: ["new bilan yaratilgan ekzemplyar orqali", "To'g'ridan-to'g'ri klass nomi orqali (ClassName.method())", "super() orqali", "prototype orqali"],
		togriJavob: 1,
	},

	// --- Getter va Setter ---
	{
		id: 46,
		bolim: "Funksiyalar va OOP",
		mavzu: "Getter va Setter",
		savol: "get fullName() { return this._name + ' ' + this._surname; } — bu nima?",
		variantlar: ["Oddiy metod", "Getter — xususiyatni o'qish uchun hisoblangan qiymat qaytaradi", "Setter", "Constructor"],
		togriJavob: 1,
	},
	{
		id: 47,
		bolim: "Funksiyalar va OOP",
		mavzu: "Getter va Setter",
		savol: "Setter metodiga nechta parametr berish kerak?",
		variantlar: ["0", "1", "2", "Istalgancha"],
		togriJavob: 1,
	},
	{
		id: 48,
		bolim: "Funksiyalar va OOP",
		mavzu: "Getter va Setter",
		savol: "obj.fullName — bu qanday chaqiriladi agar fullName getter bo'lsa?",
		variantlar: ["obj.fullName() — qavs bilan", "obj.fullName — qavssiz, xususiyat kabi", "get(obj, 'fullName')", "obj['get:fullName']"],
		togriJavob: 1,
	},
	{
		id: 49,
		bolim: "Funksiyalar va OOP",
		mavzu: "Getter va Setter",
		savol: "Setter asosiy qanday vazifani bajaradi?",
		variantlar: ["Qiymatni o'qiydi", "Qiymatni berish jarayonida validatsiya va boshqaruvni ta'minlaydi", "Xotirani tozalaydi", "Klassni instantiate qiladi"],
		togriJavob: 1,
	},
	{
		id: 50,
		bolim: "Funksiyalar va OOP",
		mavzu: "Getter va Setter",
		savol: "Getter metodi ichida return kalit so'zi ishlatilishi shartmi?",
		variantlar: ["Yo'q, ixtiyoriy", "Ha, getter albatta qiymat qaytarishi kerak", "Faqat async getter larda", "Faqat static getter larda"],
		togriJavob: 1,
	},

	// --- Optional Chaining ---
	{
		id: 51,
		bolim: "Funksiyalar va OOP",
		mavzu: "Optional Chaining",
		savol: "user?.address?.city — user undefined bo'lsa nima qaytadi?",
		variantlar: ["TypeError", "null", "undefined", "''"],
		togriJavob: 2,
	},
	{
		id: 52,
		bolim: "Funksiyalar va OOP",
		mavzu: "Optional Chaining",
		savol: "arr?.[0] — bu nima uchun ishlatiladi?",
		variantlar: [
			"Massivni filter qilish uchun",
			"arr null yoki undefined bo'lsa xatosiz birinchi elementga murojaat qilish uchun",
			"Massivning uzunligini olish uchun",
			"Massivga yangi element qo'shish uchun",
		],
		togriJavob: 1,
	},
	{
		id: 53,
		bolim: "Funksiyalar va OOP",
		mavzu: "Optional Chaining",
		savol: "obj.method?.() — bu nima qiladi?",
		variantlar: ["method mavjud bo'lsa chaqiradi, bo'lmasa undefined qaytaradi", "Har doim TypeError beradi", "method ni o'chiradi", "method ni yangi funksiya bilan almashtiradi"],
		togriJavob: 0,
	},
	{
		id: 54,
		bolim: "Funksiyalar va OOP",
		mavzu: "Optional Chaining",
		savol: "Optional chaining (?.) operatori qaysi ES versiyasida qo'shildi?",
		variantlar: ["ES2017", "ES2019", "ES2020", "ES2022"],
		togriJavob: 2,
	},
	{
		id: 55,
		bolim: "Funksiyalar va OOP",
		mavzu: "Optional Chaining",
		savol: "Nullish coalescing (??) va optional chaining (?.) birga ishlatilishi mumkinmi?",
		variantlar: ["Yo'q, ular bir-biriga zid", "Ha: user?.name ?? 'Noma'lum' — name yo'q bo'lsa 'Noma'lum' qaytadi", "Faqat TypeScript da", "Faqat class ichida"],
		togriJavob: 1,
	},

	// --- Method Injection ---
	{
		id: 56,
		bolim: "Funksiyalar va OOP",
		mavzu: "Metod Injection",
		savol: "Metod Injection asosan qanday maqsadda ishlatiladi?",
		variantlar: [
			"Funksiyani rekursiv chaqirish uchun",
			"Bir obyektga tashqaridan yangi metod yoki xizmat (service) biriktirish uchun",
			"DOM elementini o'chirish uchun",
			"CSS klassini qo'shish uchun",
		],
		togriJavob: 1,
	},
	{
		id: 57,
		bolim: "Funksiyalar va OOP",
		mavzu: "Metod Injection",
		savol: "obj.greet = function() { return 'Salom'; }; — bu nima?",
		variantlar: ["Prototip orqali meros", "Tashqaridan metod yuklash (Method Injection)", "Closure", "Destructuring"],
		togriJavob: 1,
	},
	{
		id: 58,
		bolim: "Funksiyalar va OOP",
		mavzu: "Metod Injection",
		savol: "Dependency Injection (DI) ga ko'ra qaysi yondashuv to'g'ri?",
		variantlar: [
			"Sinf ichida boshqa sinf yaratiladi (new Service())",
			"Kerakli xizmat (service) tashqaridan parametr sifatida uzatiladi",
			"Hamma narsa global o'zgaruvchi sifatida saqlanadi",
			"Faqat static metodlar ishlatiladi",
		],
		togriJavob: 1,
	},
	{
		id: 59,
		bolim: "Funksiyalar va OOP",
		mavzu: "Metod Injection",
		savol: "Metod Injection test yozishda qanday afzallik beradi?",
		variantlar: ["Hech qanday afzallik yo'q", "Sinov paytida real xizmat o'rniga mock (soxta) xizmat berib testlash osonlashadi", "Kodni tezlashtiradi", "Xotira sarfini kamaytiradi"],
		togriJavob: 1,
	},
	{
		id: 60,
		bolim: "Funksiyalar va OOP",
		mavzu: "Metod Injection",
		savol: "function sendEmail(emailService, to, body) { emailService.send(to, body); } — bu nima namunasi?",
		variantlar: ["Closure", "Rekursiya", "Dependency Injection (Metod Injection)", "Polimorfizm"],
		togriJavob: 2,
	},

	// ============================================================
	// 3-BO'LIM: DOM BLOKI
	// ============================================================

	// --- DOM va BOM tushunchasi ---
	{
		id: 61,
		bolim: "DOM bloki",
		mavzu: "DOM va BOM tushunchasi",
		savol: "DOM (Document Object Model) nima?",
		variantlar: ["CSS stillarini boshqaruvchi tizim", "HTML hujjatni daraxtsimono struktura sifatida taqdim etuvchi interfeys", "JavaScript interpretatori", "Brauzerning tarmoq moduli"],
		togriJavob: 1,
	},
	{
		id: 62,
		bolim: "DOM bloki",
		mavzu: "DOM va BOM tushunchasi",
		savol: "BOM (Browser Object Model) ning bosh (root) obyekti qaysi?",
		variantlar: ["document", "navigator", "window", "screen"],
		togriJavob: 2,
	},
	{
		id: 63,
		bolim: "DOM bloki",
		mavzu: "DOM va BOM tushunchasi",
		savol: "document obyekti BOM ichida qayerda joylashgan?",
		variantlar: ["window.document sifatida", "navigator.document sifatida", "screen.document sifatida", "location.document sifatida"],
		togriJavob: 0,
	},
	{
		id: 64,
		bolim: "DOM bloki",
		mavzu: "DOM va BOM tushunchasi",
		savol: "HTML sahifadagi har bir teg DOM-da nima sifatida ifodalanadi?",
		variantlar: ["String", "Object (Node)", "Array", "Function"],
		togriJavob: 1,
	},
	{
		id: 65,
		bolim: "DOM bloki",
		mavzu: "DOM va BOM tushunchasi",
		savol: "window.innerWidth nima qaytaradi?",
		variantlar: ["Hujjat balandligi", "Brauzer oynasining ichki kengligi (pikselda)", "Ekranning to'liq kengligi", "Scroll joylashuvi"],
		togriJavob: 1,
	},

	// --- DOM Selektorlari ---
	{
		id: 66,
		bolim: "DOM bloki",
		mavzu: "DOM Selektorlari",
		savol: "document.querySelector('.btn') — bu nima qaytaradi?",
		variantlar: ["btn klassiga ega barcha elementlar", "btn klassiga ega birinchi element", "btn ID li element", "NodeList"],
		togriJavob: 1,
	},
	{
		id: 67,
		bolim: "DOM bloki",
		mavzu: "DOM Selektorlari",
		savol: "document.querySelectorAll('p') — bu nima qaytaradi?",
		variantlar: ["Birinchi <p> element", "HTMLCollection", "NodeList (barcha <p> elementlar)", "Array"],
		togriJavob: 2,
	},
	{
		id: 68,
		bolim: "DOM bloki",
		mavzu: "DOM Selektorlari",
		savol: "getElementById va querySelector('#id') farqi nima?",
		variantlar: [
			"Hech qanday farq yo'q",
			"getElementById faqat ID bo'yicha izlaydi va biroz tezroq; querySelector CSS selektor sintaksisini qo'llaydi",
			"querySelector eskirgan",
			"getElementById NodeList qaytaradi",
		],
		togriJavob: 1,
	},
	{
		id: 69,
		bolim: "DOM bloki",
		mavzu: "DOM Selektorlari",
		savol: "document.getElementsByClassName('item') — bu nima qaytaradi?",
		variantlar: ["NodeList", "Array", "HTMLCollection (jonli to'plam)", "bitta element"],
		togriJavob: 2,
	},
	{
		id: 70,
		bolim: "DOM bloki",
		mavzu: "DOM Selektorlari",
		savol: "NodeList ni haqiqiy Array ga aylantirish uchun qaysi usul ishlatiladi?",
		variantlar: ["nodeList.toArray()", "Array.from(nodeList) yoki [...nodeList]", "nodeList.convert()", "JSON.parse(nodeList)"],
		togriJavob: 1,
	},

	// --- DOM Stil va Kontent ---
	{
		id: 71,
		bolim: "DOM bloki",
		mavzu: "DOM Stil va Kontent O'zgartirish",
		savol: "element.textContent va element.innerHTML o'rtasidagi asosiy xavfsizlik farqi nima?",
		variantlar: [
			"textContent tezroq ishlaydi",
			"textContent HTML teglarni parse qilmaydi (XSS xavfidan himoyalangan), innerHTML esa parse qiladi",
			"innerHTML faqat matn saqlaydi",
			"textContent eskirgan API",
		],
		togriJavob: 1,
	},
	{
		id: 72,
		bolim: "DOM bloki",
		mavzu: "DOM Stil va Kontent O'zgartirish",
		savol: "el.style.backgroundColor = 'red'; — bu nima qiladi?",
		variantlar: ["Element klassini o'zgartiradi", "Elementning inline CSS background-color xususiyatini o'zgartiradi", "CSS faylini o'zgartiradi", "Elementni o'chiradi"],
		togriJavob: 1,
	},
	{
		id: 73,
		bolim: "DOM bloki",
		mavzu: "DOM Stil va Kontent O'zgartirish",
		savol: "getComputedStyle(el).fontSize — bu nima qaytaradi?",
		variantlar: ["Faqat inline stilni", "CSS faylidan barcha stillari hisobga olingan haqiqiy qiymatni", "Faqat px formatida", "null"],
		togriJavob: 1,
	},
	{
		id: 74,
		bolim: "DOM bloki",
		mavzu: "DOM Stil va Kontent O'zgartirish",
		savol: "innerHTML orqali foydalanuvchi kiritgan matnni joylashtirish xavfli — sababi nima?",
		variantlar: ["innerHTML sekin ishlaydi", "XSS (Cross-Site Scripting) hujumiga yo'l ochilishi mumkin", "innerHTML faqat p tegini qo'llab-quvvatlaydi", "innerHTML standart emas"],
		togriJavob: 1,
	},
	{
		id: 75,
		bolim: "DOM bloki",
		mavzu: "DOM Stil va Kontent O'zgartirish",
		savol: "el.innerText va el.textContent farqi nima?",
		variantlar: [
			"Hech qanday farq yo'q",
			"innerText CSS bilan yashirilgan matnni e'tiborsiz qoldiradi, textContent esa barchasini qaytaradi",
			"textContent faqat input elementlari uchun",
			"innerText eskirgan",
		],
		togriJavob: 1,
	},

	// --- setAttribute / getAttribute ---
	{
		id: 76,
		bolim: "DOM bloki",
		mavzu: "setAttribute / getAttribute",
		savol: "el.setAttribute('disabled', '') — bu nima qiladi?",
		variantlar: ["Elementni DOM dan o'chiradi", "Elementga disabled atributini qo'shadi", "Elementni yashiradi", "Elementning stilini tozalaydi"],
		togriJavob: 1,
	},
	{
		id: 77,
		bolim: "DOM bloki",
		mavzu: "setAttribute / getAttribute",
		savol: "el.getAttribute('href') — bu nima qaytaradi?",
		variantlar: ["href xususiyatining DOM obyekt qiymatini", "href atributining HTML manbasidagi qiymatini (string)", "null (getAttribute ishlamaydi)", "undefined"],
		togriJavob: 1,
	},
	{
		id: 78,
		bolim: "DOM bloki",
		mavzu: "setAttribute / getAttribute",
		savol: "el.removeAttribute('class') — bu nima qiladi?",
		variantlar: ["class atributini o'chiradi (barcha klasslar ketadi)", "Faqat birinchi klassni olib tashlaydi", "Elementni o'chiradi", "class qiymatini bo'sh string ga qo'yadi"],
		togriJavob: 0,
	},
	{
		id: 79,
		bolim: "DOM bloki",
		mavzu: "setAttribute / getAttribute",
		savol: "data-* atributlariga JavaScript orqali qanday murojaat qilinadi?",
		variantlar: ["el.getAttribute('data-foo') yoki el.dataset.foo", "el.data.foo", "el.customAttribute.foo", "el['data-foo'] faqat"],
		togriJavob: 0,
	},
	{
		id: 80,
		bolim: "DOM bloki",
		mavzu: "setAttribute / getAttribute",
		savol: "el.hasAttribute('readonly') — bu nima qaytaradi?",
		variantlar: ["Atribut qiymati (string)", "true yoki false", "Atribut indeksi", "null yoki undefined"],
		togriJavob: 1,
	},

	// --- Element yaratish va o'chirish ---
	{
		id: 81,
		bolim: "DOM bloki",
		mavzu: "Element Yaratish va O'chirish",
		savol: "document.createElement('div') — bu nima qaytaradi?",
		variantlar: ["Sahifaga div qo'shadi", "Yangi div DOM nodeni yaratadi (lekin sahifaga qo'shmaydi)", "Mavjud birinchi div ni topadi", "String qaytaradi"],
		togriJavob: 1,
	},
	{
		id: 82,
		bolim: "DOM bloki",
		mavzu: "Element Yaratish va O'chirish",
		savol: "parent.appendChild(child) — bu nima qiladi?",
		variantlar: ["child ni parent dan oldin qo'shadi", "child ni parent ning so'nggi farzandi sifatida qo'shadi", "child ni o'chiradi", "parent ni child ga aylantiradi"],
		togriJavob: 1,
	},
	{
		id: 83,
		bolim: "DOM bloki",
		mavzu: "Element Yaratish va O'chirish",
		savol: "el.remove() — bu nima qiladi?",
		variantlar: ["Elementni yashiradi (display:none)", "Elementni DOM dan to'liq olib tashlaydi", "Elementning farzandlarini o'chiradi", "Elementni disabled qiladi"],
		togriJavob: 1,
	},
	{
		id: 84,
		bolim: "DOM bloki",
		mavzu: "Element Yaratish va O'chirish",
		savol: "parent.insertBefore(newEl, referenceEl) — bu nima qiladi?",
		variantlar: ["newEl ni parent ning oxiriga qo'shadi", "newEl ni referenceEl dan oldin qo'shadi", "referenceEl ni o'chirib newEl qo'yadi", "newEl ni referenceEl dan keyin qo'shadi"],
		togriJavob: 1,
	},
	{
		id: 85,
		bolim: "DOM bloki",
		mavzu: "Element Yaratish va O'chirish",
		savol: "DocumentFragment nima uchun ishlatiladi?",
		variantlar: [
			"CSS animatsiyalari uchun",
			"Ko'p elementni to'plab bitta hamlada DOM ga qo'shish (reflow minimalizatsiyasi) uchun",
			"Ma'lumotlar bazasiga so'rov yuborish uchun",
			"Iframe yaratish uchun",
		],
		togriJavob: 1,
	},

	// --- classList ---
	{
		id: 86,
		bolim: "DOM bloki",
		mavzu: "classList (add/remove)",
		savol: "el.classList.add('active') — bu nima qiladi?",
		variantlar: ["Barcha klasslarni o'chirib 'active' qo'yadi", "'active' klassini mavjud klasslarga qo'shadi", "Elementni aktivlashtiradi (click triggerlaydi)", "CSS faylida .active ni yaratadi"],
		togriJavob: 1,
	},
	{
		id: 87,
		bolim: "DOM bloki",
		mavzu: "classList (add/remove)",
		savol: "el.classList.toggle('open') — bu nima qiladi?",
		variantlar: ["'open' har doim qo'shiladi", "'open' mavjud bo'lsa olib tashlaydi, bo'lmasa qo'shadi", "Elementni ko'rsatadi/yashiradi", "Xato beradi"],
		togriJavob: 1,
	},
	{
		id: 88,
		bolim: "DOM bloki",
		mavzu: "classList (add/remove)",
		savol: "el.classList.contains('hidden') — bu nima qaytaradi?",
		variantlar: ["'hidden' klassining CSS qiymatini", "true yoki false", "Klass indeksini", "undefined"],
		togriJavob: 1,
	},
	{
		id: 89,
		bolim: "DOM bloki",
		mavzu: "classList (add/remove)",
		savol: "el.classList.replace('old', 'new') — bu nima qiladi?",
		variantlar: ["'old' ni topsa 'new' bilan almashtiradi", "Barcha klasslarni 'new' bilan almashtiradi", "Xato beradi", "Hech narsa qilmaydi"],
		togriJavob: 0,
	},
	{
		id: 90,
		bolim: "DOM bloki",
		mavzu: "classList (add/remove)",
		savol: "el.className = 'a b c' va el.classList.add('a','b','c') — farqi nima?",
		variantlar: [
			"Hech qanday farq yo'q",
			"className barcha mavjud klasslarni o'chirib yangilaydi; classList.add mavjud klasslarga qo'shadi",
			"classList.add sekinroq",
			"className faqat bitta klass qabul qiladi",
		],
		togriJavob: 1,
	},

	// --- Hodisalar ---
	{
		id: 91,
		bolim: "DOM bloki",
		mavzu: "Hodisalar (addEventListener)",
		savol: "addEventListener ning uchinchi parametri (true/false) nima uchun?",
		variantlar: ["Hodisani bir marta ishlash uchun", "Capturing (true) yoki Bubbling (false) rejimini belgilash uchun", "Hodisani to'xtatish uchun", "Async hodisa uchun"],
		togriJavob: 1,
	},
	{
		id: 92,
		bolim: "DOM bloki",
		mavzu: "Hodisalar (addEventListener)",
		savol: "Event Bubbling nima?",
		variantlar: ["Hodisa farzand elementdan boshlanib ota elementlarga tarqalishi", "Hodisa ota elementdan farzandlarga tarqalishi", "Hodisaning bekor qilinishi", "Hodisaning ikki marta ishlashi"],
		togriJavob: 0,
	},
	{
		id: 93,
		bolim: "DOM bloki",
		mavzu: "Hodisalar (addEventListener)",
		savol: "event.stopPropagation() nima qiladi?",
		variantlar: ["Forma yuborilishini to'xtatadi", "Hodisaning ota elementlarga tarqalishini (bubbling/capturing) to'xtatadi", "Hodisani qayta ishga tushiradi", "Elementni DOM dan olib tashlaydi"],
		togriJavob: 1,
	},
	{
		id: 94,
		bolim: "DOM bloki",
		mavzu: "Hodisalar (addEventListener)",
		savol: "Event Delegation (Hodisa delegatsiyasi) nima?",
		variantlar: [
			"Har bir farzand elementga alohida listener qo'shish",
			"Bitta ota elementga listener qo'yib, farzandlardan kelgan hodisalarni boshqarish",
			"Hodisani o'chirish",
			"Hodisani asinxron boshqarish",
		],
		togriJavob: 1,
	},
	{
		id: 95,
		bolim: "DOM bloki",
		mavzu: "Hodisalar (addEventListener)",
		savol: "{ once: true } opsiyasi addEventListener ga berilsa nima bo'ladi?",
		variantlar: ["Hodisa bir marta ishlagandan so'ng listener avtomatik o'chiriladi", "Hodisa faqat capturing rejimida ishlaydi", "Hodisa asinxron ishlaydi", "Hech qanday ta'siri yo'q"],
		togriJavob: 0,
	},

	// ============================================================
	// 4-BO'LIM: BOM VA BRAUZER API-LARI
	// ============================================================

	// --- window va location ---
	{
		id: 96,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "window va location",
		savol: "window.location.href — bu nima qaytaradi?",
		variantlar: ["Sahifaning sarlavhasi (title)", "Joriy sahifaning to'liq URL manzili", "Domenning faqat nomi", "HTTP status kodi"],
		togriJavob: 1,
	},
	{
		id: 97,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "window va location",
		savol: "window.location.reload() nima qiladi?",
		variantlar: ["Brauzer tarixini tozalaydi", "Joriy sahifani qayta yuklaydi", "Bosh sahifaga qaytadi", "Sahifani yopadi"],
		togriJavob: 1,
	},
	{
		id: 98,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "window va location",
		savol: "window.history.back() — bu nima qiladi?",
		variantlar: ["Sahifani yangilaydi", "Brauzer tarixida bir sahifa orqaga qaytadi", "Brauzer tarixini o'chiradi", "Yangi sahifa ochadi"],
		togriJavob: 1,
	},
	{
		id: 99,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "window va location",
		savol: "window.open('https://example.com', '_blank') — bu nima qiladi?",
		variantlar: ["Joriy oynada URLni ochadi", "Yangi tab yoki oynada URLni ochadi", "URLni yuklab oladi", "iframe yaratadi"],
		togriJavob: 1,
	},
	{
		id: 100,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "window va location",
		savol: "location.search nima qaytaradi?",
		variantlar: ["URL dagi hash qismni (#...)", "URL dagi query string qismini (?key=val&...)", "URL dagi protokolni (https:)", "URL dagi yo'lni (/path)"],
		togriJavob: 1,
	},

	// --- new Date() ---
	{
		id: 101,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "new Date()",
		savol: "new Date() — bu nima qaytaradi?",
		variantlar: ["Faqat sanani (kun, oy, yil)", "Joriy sana va vaqtni ifodalovchi Date obyektini", "Unix timestamp (raqam)", "ISO string"],
		togriJavob: 1,
	},
	{
		id: 102,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "new Date()",
		savol: "Date.now() nima qaytaradi?",
		variantlar: ["Date obyekti", "Joriy Unix timestamp (millisekundlarda)", "ISO 8601 formati", "Lokal sana string"],
		togriJavob: 1,
	},
	{
		id: 103,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "new Date()",
		savol: "const d = new Date(); d.getMonth() — yanvar oyi uchun nima qaytaradi?",
		variantlar: ["1", "0", "January", "01"],
		togriJavob: 1,
	},
	{
		id: 104,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "new Date()",
		savol: "d.toLocaleDateString('uz-UZ') — bu nima qiladi?",
		variantlar: ["Sanani ISO formatiga o'giradi", "Sanani O'zbek lokal formatida string sifatida qaytaradi", "Vaqtni UTC ga aylantiradi", "Xato beradi"],
		togriJavob: 1,
	},
	{
		id: 105,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "new Date()",
		savol: "Ikkita sana orasidagi kunlar sonini topish uchun qaysi amal qilinadi?",
		variantlar: ["date1 - date2 (millisekund farqi olinib 86400000 ga bo'linadi)", "date1.compare(date2)", "Math.abs(date1, date2)", "new Date(date1 - date2)"],
		togriJavob: 0,
	},

	// --- localStorage ---
	{
		id: 106,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "localStorage",
		savol: "localStorage va sessionStorage o'rtasidagi asosiy farq nima?",
		variantlar: [
			"localStorage tezroq, sessionStorage sekinroq",
			"localStorage brauzer yopilganda saqlanib qoladi, sessionStorage tab/oyna yopilganda o'chadi",
			"sessionStorage katta hajm saqlaydi",
			"Hech qanday farq yo'q",
		],
		togriJavob: 1,
	},
	{
		id: 107,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "localStorage",
		savol: "localStorage.setItem('key', value) — value obyekt bo'lsa nima qilish kerak?",
		variantlar: ["To'g'ridan-to'g'ri uzatish", "JSON.stringify(value) orqali string ga o'tkazib saqlash", "Array.from(value) qilish", "btoa(value) qilish"],
		togriJavob: 1,
	},
	{
		id: 108,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "localStorage",
		savol: "localStorage.removeItem('key') nima qiladi?",
		variantlar: ["Butun localStorage ni tozalaydi", "Faqat 'key' ga tegishli yozuvni o'chiradi", "Qiymatni null ga o'zgartiradi", "Xato beradi"],
		togriJavob: 1,
	},
	{
		id: 109,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "localStorage",
		savol: "localStorage.clear() nima qiladi?",
		variantlar: ["Bitta elementni o'chiradi", "Joriy domain uchun barcha localStorage ma'lumotlarini o'chiradi", "Cookie larni tozalaydi", "Session ni tugatadi"],
		togriJavob: 1,
	},
	{
		id: 110,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "localStorage",
		savol: "localStorage.length nima qaytaradi?",
		variantlar: ["Saqlangan ma'lumotlar hajmi (baytda)", "Saqlangan kalit-qiymat juftlari soni", "Oxirgi saqlash vaqti", "Mavjud bo'sh joy miqdori"],
		togriJavob: 1,
	},

	// ============================================================
	// 5-BO'LIM: ASINXRON JAVASCRIPT BLOKI
	// ============================================================

	// --- Sinxron va Asinxron ---
	{
		id: 111,
		bolim: "Asinxron JS bloki",
		mavzu: "Sinxron va Asinxron JS",
		savol: "JavaScript qanday turdagi (threading) til?",
		variantlar: ["Ko'p oqimli (multi-threaded)", "Bitta oqimli (single-threaded)", "Parallel ishlovchi", "Server-side faqat"],
		togriJavob: 1,
	},
	{
		id: 112,
		bolim: "Asinxron JS bloki",
		mavzu: "Sinxron va Asinxron JS",
		savol: "Event Loop (Hodisa halqasi) ning asosiy vazifasi nima?",
		variantlar: ["DOM elementlarini render qilish", "Call Stack bo'sh bo'lganda Callback Queue dan vazifalarni olib Stack ga qo'yish", "Tarmoq so'rovlarini yuborish", "setTimeout ni hisoblash"],
		togriJavob: 1,
	},
	{
		id: 113,
		bolim: "Asinxron JS bloki",
		mavzu: "Sinxron va Asinxron JS",
		savol: "Quyidagi kod qaysi tartibda chiqadi?\nconsole.log('A');\nsetTimeout(() => console.log('B'), 0);\nconsole.log('C');",
		variantlar: ["A, B, C", "A, C, B", "B, A, C", "C, A, B"],
		togriJavob: 1,
	},
	{
		id: 114,
		bolim: "Asinxron JS bloki",
		mavzu: "Sinxron va Asinxron JS",
		savol: "Microtask Queue (Mikrovazifalar navbati) ga nimalar tushadi?",
		variantlar: ["setTimeout callbacklari", "setInterval callbacklari", "Promise .then() / .catch() callbacklari va queueMicrotask", "DOM hodisalari"],
		togriJavob: 2,
	},
	{
		id: 115,
		bolim: "Asinxron JS bloki",
		mavzu: "Sinxron va Asinxron JS",
		savol: "Microtask Queue va Macrotask Queue dan qaysi biri birinchi bajariladi?",
		variantlar: ["Macrotask (setTimeout avval bajariladi)", "Microtask (Promise callbacklari setTimeout dan avval)", "Ikkalasi teng ustuvorlikda", "Random tartibda"],
		togriJavob: 1,
	},

	// --- setTimeout va setInterval ---
	{
		id: 116,
		bolim: "Asinxron JS bloki",
		mavzu: "setTimeout va setInterval",
		savol: "setTimeout(() => {}, 1000) — bu nima qaytaradi?",
		variantlar: ["Promise", "Numeric ID (timeout ID)", "undefined", "Boolean"],
		togriJavob: 1,
	},
	{
		id: 117,
		bolim: "Asinxron JS bloki",
		mavzu: "setTimeout va setInterval",
		savol: "clearTimeout(id) nima qiladi?",
		variantlar: ["Barcha timeout larni bekor qiladi", "Berilgan ID ga mos timeout ni bekor qiladi (agar hali ishlamagan bo'lsa)", "setInterval ni to'xtatadi", "Event loop ni tozalaydi"],
		togriJavob: 1,
	},
	{
		id: 118,
		bolim: "Asinxron JS bloki",
		mavzu: "setTimeout va setInterval",
		savol: "setInterval va setTimeout o'rtasidagi farq nima?",
		variantlar: [
			"setInterval faqat bir marta ishlaydi",
			"setTimeout faqat bir marta, setInterval belgilangan vaqt oralig'ida qayta-qayta ishlaydi",
			"Ular bir xil, faqat nomi farqli",
			"setInterval tezroq ishlaydi",
		],
		togriJavob: 1,
	},
	{
		id: 119,
		bolim: "Asinxron JS bloki",
		mavzu: "setTimeout va setInterval",
		savol: "setTimeout(fn, 0) — fn qachon ishlaydi?",
		variantlar: ["Darhol, sinxron ravishda", "Call Stack bo'shagandan keyin, macrotask sifatida", "Hech qachon ishlamaydi", "Keyingi sahifa yuklashda"],
		togriJavob: 1,
	},
	{
		id: 120,
		bolim: "Asinxron JS bloki",
		mavzu: "setTimeout va setInterval",
		savol: "requestAnimationFrame(fn) qaysi holatda ishlatilish tavsiya etiladi?",
		variantlar: [
			"API so'rovlari uchun",
			"Silliq animatsiyalar uchun (ekranning yangilanish chastotasiga sinxronlashgan)",
			"setTimeout o'rniga har qanday kechiktirish uchun",
			"localStorage ni tozalash uchun",
		],
		togriJavob: 1,
	},

	// --- Promise ---
	{
		id: 121,
		bolim: "Asinxron JS bloki",
		mavzu: "Promise lar",
		savol: "Promise ning uchta holati qaysilar?",
		variantlar: ["start, running, done", "pending, fulfilled, rejected", "loading, success, error", "open, closed, settled"],
		togriJavob: 1,
	},
	{
		id: 122,
		bolim: "Asinxron JS bloki",
		mavzu: "Promise lar",
		savol: "Promise.all([p1, p2, p3]) qanday ishlaydi?",
		variantlar: [
			"Birinchi fulfilled bo'lgan promise ni qaytaradi",
			"Barcha promise lar fulfilled bo'lsa natijalar massivini qaytaradi; bittasi rejected bo'lsa catch ishga tushadi",
			"Barcha promise lar rejected bo'lsa natija qaytaradi",
			"Faqat birinchi promise ni kutadi",
		],
		togriJavob: 1,
	},
	{
		id: 123,
		bolim: "Asinxron JS bloki",
		mavzu: "Promise lar",
		savol: "Promise.race([p1, p2]) nima qaytaradi?",
		variantlar: [
			"Barcha promise lar tugashi kutilib natijalar massivi",
			"Birinchi yakunlangan (fulfilled yoki rejected) promise ning natijasi",
			"Faqat fulfilled bo'lgan birinchi natija",
			"Har doim p1 ning natijasi",
		],
		togriJavob: 1,
	},
	{
		id: 124,
		bolim: "Asinxron JS bloki",
		mavzu: "Promise lar",
		savol: ".then(fn) da fn qachon chaqiriladi?",
		variantlar: ["Promise rejected bo'lganda", "Promise fulfilled bo'lganda", "Promise hali pending bo'lganda", "Promise yaratilganda darhol"],
		togriJavob: 1,
	},
	{
		id: 125,
		bolim: "Asinxron JS bloki",
		mavzu: "Promise lar",
		savol: "Promise.allSettled() va Promise.all() o'rtasidagi farq nima?",
		variantlar: [
			"Hech qanday farq yo'q",
			"allSettled barcha promise lar yakunlanishini kutadi va har birining holati (fulfilled/rejected) ni qaytaradi; all bitta rejected da to'xtaydi",
			"allSettled faqat rejected promise lar uchun",
			"all tezroq ishlaydi",
		],
		togriJavob: 1,
	},

	// --- Async / Await ---
	{
		id: 126,
		bolim: "Asinxron JS bloki",
		mavzu: "Async / Await",
		savol: "async funksiya doimo nima qaytaradi?",
		variantlar: ["undefined", "Promise", "Callback", "Generator"],
		togriJavob: 1,
	},
	{
		id: 127,
		bolim: "Asinxron JS bloki",
		mavzu: "Async / Await",
		savol: "await kalit so'zini qayerda ishlatish mumkin?",
		variantlar: ["Har qanday funksiya ichida", "Faqat async deb belgilangan funksiya ichida", "Faqat global scope da", "Faqat class metodlarida"],
		togriJavob: 1,
	},
	{
		id: 128,
		bolim: "Asinxron JS bloki",
		mavzu: "Async / Await",
		savol: "const data = await fetch(url); — fetch rejected bo'lsa nima bo'ladi?",
		variantlar: ["data = null bo'ladi", "try...catch yo'q bo'lsa, xato tashlanadi (unhandled rejection)", "data = undefined bo'ladi", "Funksiya to'xtaydi va qayta urinadi"],
		togriJavob: 1,
	},
	{
		id: 129,
		bolim: "Asinxron JS bloki",
		mavzu: "Async / Await",
		savol: "Parallel asinxron so'rovlarni await bilan samarali bajarish uchun qaysi usul to'g'ri?",
		variantlar: ["await req1; await req2; (ketma-ket)", "const [r1, r2] = await Promise.all([req1, req2]); (parallel)", "setTimeout orqali", "async/await parallel ishlay olmaydi"],
		togriJavob: 1,
	},
	{
		id: 130,
		bolim: "Asinxron JS bloki",
		mavzu: "Async / Await",
		savol: "async/await va Promise .then() zanjiri bir xil ishmi?",
		variantlar: [
			"Yo'q, async/await ko'proq Promise qaytaradi",
			"Ha, async/await Promise .then() ning sintaktik shakar (syntactic sugar) i",
			"async/await faqat Node.js da ishlaydi",
			".then() zanjiri tezroq ishlaydi",
		],
		togriJavob: 1,
	},

	// --- AJAX va API ---
	{
		id: 131,
		bolim: "Asinxron JS bloki",
		mavzu: "AJAX va API",
		savol: "AJAX nima uchun ishlatiladi?",
		variantlar: ["CSS animatsiyalari uchun", "Sahifani qayta yuklamasdan serverdan ma'lumot olish/yuborish uchun", "DOM manipulyatsiyasi uchun", "localStorage bilan ishlash uchun"],
		togriJavob: 1,
	},
	{
		id: 132,
		bolim: "Asinxron JS bloki",
		mavzu: "AJAX va API",
		savol: "REST API da GET so'rovi qanday maqsadda ishlatiladi?",
		variantlar: ["Ma'lumot yaratish uchun", "Ma'lumotni o'chirish uchun", "Ma'lumot olish (o'qish) uchun", "Ma'lumotni to'liq yangilash uchun"],
		togriJavob: 2,
	},
	{
		id: 133,
		bolim: "Asinxron JS bloki",
		mavzu: "AJAX va API",
		savol: "HTTP 404 status kodi nima anglatadi?",
		variantlar: ["Server xatosi", "Muvaffaqiyatli javob", "Resurs topilmadi", "Autentifikatsiya xatosi"],
		togriJavob: 2,
	},
	{
		id: 134,
		bolim: "Asinxron JS bloki",
		mavzu: "AJAX va API",
		savol: "CORS (Cross-Origin Resource Sharing) nima?",
		variantlar: [
			"JavaScript xotirani boshqarish mexanizmi",
			"Brauzerning boshqa domendan resurs so'rashini boshqaruvchi xavfsizlik mexanizmi",
			"CSS orqali cross-browser muvofiqlik",
			"API autentifikatsiya standarti",
		],
		togriJavob: 1,
	},
	{
		id: 135,
		bolim: "Asinxron JS bloki",
		mavzu: "AJAX va API",
		savol: "HTTP 201 status kodi nima anglatadi?",
		variantlar: ["Ma'lumot muvaffaqiyatli o'chirildi", "Ma'lumot muvaffaqiyatli yaratildi", "So'rov keshdan qaytarildi", "Server xato"],
		togriJavob: 1,
	},

	// --- Fetch API ---
	{
		id: 136,
		bolim: "Asinxron JS bloki",
		mavzu: "Fetch API",
		savol: "fetch() funksiyasi nima qaytaradi?",
		variantlar: ["Ma'lumotni to'g'ridan-to'g'ri", "Response obyektini o'z ichiga olgan Promise", "XMLHttpRequest obyekti", "JSON ma'lumot"],
		togriJavob: 1,
	},
	{
		id: 137,
		bolim: "Asinxron JS bloki",
		mavzu: "Fetch API",
		savol: "fetch dan JSON ma'lumot olish uchun qanday qilinadi?",
		variantlar: ["const data = fetch(url).json();", "const res = await fetch(url); const data = await res.json();", "const data = await fetch(url);", "fetch(url, { type: 'json' });"],
		togriJavob: 1,
	},
	{
		id: 138,
		bolim: "Asinxron JS bloki",
		mavzu: "Fetch API",
		savol: "fetch() qachon rejected Promise qaytaradi?",
		variantlar: ["Server 404 qaytarganda", "Server 500 qaytarganda", "Tarmoq xatosi bo'lganda (internet yo'q, DNS xatosi va h.k.)", "Response bo'sh bo'lganda"],
		togriJavob: 2,
	},
	{
		id: 139,
		bolim: "Asinxron JS bloki",
		mavzu: "Fetch API",
		savol: "POST so'rovini fetch bilan yuborish uchun qaysi konfiguratsiya to'g'ri?",
		variantlar: [
			"fetch(url, { type: 'POST', data: JSON.stringify(body) })",
			"fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) })",
			"fetch.post(url, body)",
			"fetch(url).post(body)",
		],
		togriJavob: 1,
	},
	{
		id: 140,
		bolim: "Asinxron JS bloki",
		mavzu: "Fetch API",
		savol: "response.ok xususiyati nima bildiradi?",
		variantlar: ["Response JSON formatida ekanligi", "HTTP status kodi 200-299 oralig'ida ekanligi (muvaffaqiyatli so'rov)", "So'rov keshdan kelgani", "Response bo'sh emasligi"],
		togriJavob: 1,
	},

	// ============================================================
	// QO'SHIMCHA ARALASH SAVOLLAR (id: 141-200)
	// ============================================================

	{
		id: 141,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Stack va Heap",
		savol: "Call Stack to'lib ketsa qanday xato yuz beradi?",
		variantlar: ["HeapOverflowError", "RangeError: Maximum call stack size exceeded", "TypeError", "MemoryError"],
		togriJavob: 1,
	},
	{
		id: 142,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Deep Copy va Shallow Copy",
		savol: "structuredClone(obj) — bu qanday nusxa oladi?",
		variantlar: ["Shallow Copy", "Deep Copy (zamonaviy va to'g'ri usul)", "Reference Copy", "Immutable Copy"],
		togriJavob: 1,
	},
	{
		id: 143,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Destructuring",
		savol: "const [first, ...rest] = [1, 2, 3, 4]; — rest nima?",
		variantlar: ["[1, 2, 3, 4]", "[2, 3, 4]", "2", "[1]"],
		togriJavob: 1,
	},
	{
		id: 144,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "RegEx",
		savol: "RegEx dagi ^ belgisi nima anglatadi?",
		variantlar: ["Matn oxiri", "Matn boshi", "Ixtiyoriy belgi", "Takrorlanish"],
		togriJavob: 1,
	},
	{
		id: 145,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Throw Errors",
		savol: "TypeError nima holatlarda yuz beradi?",
		variantlar: [
			"Mavjud bo'lmagan o'zgaruvchiga murojaat",
			"Qiymat noto'g'ri tipda ishlatilganda (masalan, undefined ni funksiya sifatida chaqirish)",
			"Massiv chegarasidan chiqish",
			"Sintaksis xatosi",
		],
		togriJavob: 1,
	},
	{
		id: 146,
		bolim: "Funksiyalar va OOP",
		mavzu: "Callback Funksiyalar",
		savol: "arr.sort(compareFn) — compareFn callback nima qaytarishi kerak?",
		variantlar: ["true yoki false", "Manfiy, nol, yoki musbat son", "Saralangan element", "undefined"],
		togriJavob: 1,
	},
	{
		id: 147,
		bolim: "Funksiyalar va OOP",
		mavzu: "High Order Functions",
		savol: "[1,2,3].map(x => x * 2) — natija nima?",
		variantlar: ["[1, 2, 3]", "[2, 4, 6]", "6", "true"],
		togriJavob: 1,
	},
	{
		id: 148,
		bolim: "Funksiyalar va OOP",
		mavzu: "Closure",
		savol: "Quyidagi for loop natijasi nima? (var ishlatilsa)\nfor (var i = 0; i < 3; i++) { setTimeout(() => console.log(i), 0); }",
		variantlar: ["0, 1, 2", "3, 3, 3", "0, 0, 0", "1, 2, 3"],
		togriJavob: 1,
	},
	{
		id: 149,
		bolim: "Funksiyalar va OOP",
		mavzu: "Class lar",
		savol: "JavaScript klasslarida haqiqiy 'private' maydon yaratish uchun qanday sintaksis ishlatiladi?",
		variantlar: ["_xususiy", "private xususiy", "#xususiy", "__xususiy__"],
		togriJavob: 2,
	},
	{
		id: 150,
		bolim: "Funksiyalar va OOP",
		mavzu: "Getter va Setter",
		savol: "Object.defineProperty(obj, 'x', { get() {...}, set(v) {...} }) — bu nima?",
		variantlar: ["Klassda getter/setter aniqlash", "Oddiy obyektda getter/setter aniqlashning past darajali usuli", "Prototip zanjirini o'zgartirish", "Xususiyatni o'chirish"],
		togriJavob: 1,
	},
	{
		id: 151,
		bolim: "Funksiyalar va OOP",
		mavzu: "Optional Chaining",
		savol: "null?.toString() — nima qaytaradi?",
		variantlar: ["TypeError", "'null'", "undefined", "null"],
		togriJavob: 2,
	},
	{
		id: 152,
		bolim: "Funksiyalar va OOP",
		mavzu: "Metod Injection",
		savol: "Function.prototype.bind(thisArg) metodi nima qiladi?",
		variantlar: ["Funksiyani darhol chaqiradi", "this konteksti bog'langan yangi funksiya qaytaradi", "Funksiyani o'chiradi", "Funksiyaga yangi parametr qo'shadi"],
		togriJavob: 1,
	},
	{
		id: 153,
		bolim: "DOM bloki",
		mavzu: "DOM Selektorlari",
		savol: "el.closest('.container') — bu nima qiladi?",
		variantlar: [
			"Eng yaqin farzand elementni topadi",
			"el dan boshlab yuqoriga qarab '.container' ga mos birinchi ota elementni topadi",
			"Barcha '.container' elementlarni qaytaradi",
			"document dagi birinchi '.container' ni topadi",
		],
		togriJavob: 1,
	},
	{
		id: 154,
		bolim: "DOM bloki",
		mavzu: "DOM Stil va Kontent O'zgartirish",
		savol: "el.scrollIntoView() nima qiladi?",
		variantlar: ["Elementni o'chiradi", "Sahifani scroll qilib elementni ko'rinarli joyga olib keladi", "Elementni animatsiyalaydi", "Elementni DOM dan olib tashlaydi"],
		togriJavob: 1,
	},
	{
		id: 155,
		bolim: "DOM bloki",
		mavzu: "setAttribute / getAttribute",
		savol: "el.dataset.userId — bu qaysi HTML atributiga mos?",
		variantlar: ["data-userId", "data-user-id", "userId", "data_user_id"],
		togriJavob: 1,
	},
	{
		id: 156,
		bolim: "DOM bloki",
		mavzu: "Element Yaratish va O'chirish",
		savol: "el.innerHTML = '' — bu nima qiladi?",
		variantlar: ["Elementni o'chiradi", "Elementning barcha ichki kontentini o'chiradi", "Elementni yashiradi", "Elementga bo'sh string qo'shadi"],
		togriJavob: 1,
	},
	{
		id: 157,
		bolim: "DOM bloki",
		mavzu: "classList (add/remove)",
		savol: "el.classList.remove('a', 'b', 'c') — bu nima qiladi?",
		variantlar: ["Faqat 'a' klassini olib tashlaydi", "'a', 'b' va 'c' klasslarini birvaqtda olib tashlaydi", "Barcha klasslarni olib tashlaydi", "Xato beradi"],
		togriJavob: 1,
	},
	{
		id: 158,
		bolim: "DOM bloki",
		mavzu: "Hodisalar (addEventListener)",
		savol: "event.target va event.currentTarget farqi nima?",
		variantlar: [
			"Farqi yo'q",
			"target — hodisa boshlangan asl element; currentTarget — listener qo'shilgan element",
			"currentTarget — hodisa boshlangan asl element; target — listener qo'shilgan element",
			"target faqat click hodisasida mavjud",
		],
		togriJavob: 1,
	},
	{
		id: 159,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "window va location",
		savol: "window.alert('Salom!') nima qiladi?",
		variantlar: ["Consolega chiqaradi", "Foydalanuvchiga modal dialog oyna ko'rsatadi", "Sahifani qayta yuklaydi", "Xato beradi"],
		togriJavob: 1,
	},
	{
		id: 160,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "new Date()",
		savol: "d.getFullYear() — bu nima qaytaradi?",
		variantlar: ["2 xonali yil (masalan, '25')", "4 xonali yil (masalan, 2025)", "Yilning kun raqami", "Moliyaviy yil"],
		togriJavob: 1,
	},
	{
		id: 161,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "localStorage",
		savol: "Inkognito (Private) rejimida localStorage ishlaydi, lekin qanday?",
		variantlar: ["Umuman ishlamaydi", "Ishlaydi, lekin tab yopilganda barcha ma'lumotlar o'chadi", "Oddiy rejimdan farqi yo'q", "Faqat o'qish mumkin, yozish mumkin emas"],
		togriJavob: 1,
	},
	{
		id: 162,
		bolim: "Asinxron JS bloki",
		mavzu: "Promise lar",
		savol: "Promise.resolve(42) nima qaytaradi?",
		variantlar: ["42", "fulfilled holatdagi Promise (qiymati 42)", "undefined", "Error"],
		togriJavob: 1,
	},
	{
		id: 163,
		bolim: "Asinxron JS bloki",
		mavzu: "Async / Await",
		savol: "Async funksiya ichida return 5 qilinsa, tashqaridagi kod nima oladi?",
		variantlar: ["5 raqamini to'g'ridan-to'g'ri", "5 ni o'z ichiga olgan fulfilled Promise", "undefined", "Error"],
		togriJavob: 1,
	},
	{
		id: 164,
		bolim: "Asinxron JS bloki",
		mavzu: "Fetch API",
		savol: "fetch so'roviga Authorization header qo'shish uchun qanday qilinadi?",
		variantlar: [
			"fetch(url, { auth: 'Bearer token' })",
			"fetch(url, { headers: { 'Authorization': 'Bearer token' } })",
			"fetch.setHeader('Authorization', 'Bearer token')",
			"fetch(url).auth('Bearer token')",
		],
		togriJavob: 1,
	},
	{
		id: 165,
		bolim: "Asinxron JS bloki",
		mavzu: "AJAX va API",
		savol: "HTTP DELETE so'rovi qanday maqsadda ishlatiladi?",
		variantlar: ["Ma'lumot olish", "Ma'lumot yangilash", "Ma'lumot o'chirish", "Ma'lumot yaratish"],
		togriJavob: 2,
	},
	{
		id: 166,
		bolim: "Funksiyalar va OOP",
		mavzu: "Closure",
		savol: "Memoization (natijalarni keshga saqlash) texnikasi closure bilan qanday bog'liq?",
		variantlar: [
			"Bog'liqligi yo'q",
			"Closure yordamida hisoblangan natijalar ichki o'zgaruvchida saqlanadi va bir xil argumentda qayta hisoblanmaydi",
			"Memoization faqat rekursiv funksiyalarda ishlaydi",
			"Memoization localStorage ishlatadi",
		],
		togriJavob: 1,
	},
	{
		id: 167,
		bolim: "DOM bloki",
		mavzu: "DOM va BOM tushunchasi",
		savol: "DOMContentLoaded va load hodisalari o'rtasidagi farq nima?",
		variantlar: [
			"Hech qanday farq yo'q",
			"DOMContentLoaded HTML parse qilinganda ishga tushadi; load barcha resurslar (rasmlar, CSS) yuklanganda",
			"load HTML parse qilinganda; DOMContentLoaded rasmlar yuklanganda",
			"DOMContentLoaded faqat body uchun",
		],
		togriJavob: 1,
	},
	{
		id: 168,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Destructuring",
		savol: "Funksiya parametrlarida default qiymat destructuring bilan qanday yoziladi?",
		variantlar: ["function f({ x, y }) { let x = x || 0; }", "function f({ x = 0, y = 0 } = {}) { }", "function f(obj) { obj.x = obj.x ?? 0; }", "Mumkin emas"],
		togriJavob: 1,
	},
	{
		id: 169,
		bolim: "Funksiyalar va OOP",
		mavzu: "High Order Functions",
		savol: "Array.prototype.flatMap() metodi nima qiladi?",
		variantlar: ["Massivni tekislashtiradi (flat) va keyin map qiladi", "Avval map qiladi, so'ng bir darajani tekislashtiradi", "filter va map ni birlashtiradi", "Massivni 2D ga aylantiradi"],
		togriJavob: 1,
	},
	{
		id: 170,
		bolim: "Asinxron JS bloki",
		mavzu: "setTimeout va setInterval",
		savol: "setInterval ni to'xtatish uchun qaysi funksiya ishlatiladi?",
		variantlar: ["clearTimeout(id)", "clearInterval(id)", "stopInterval(id)", "cancelInterval(id)"],
		togriJavob: 1,
	},
	{
		id: 171,
		bolim: "Funksiyalar va OOP",
		mavzu: "Class lar",
		savol: "class Animal { } class Dog extends Animal { } — Dog.prototype.__proto__ nimaga teng?",
		variantlar: ["Object.prototype", "Animal.prototype", "Dog.prototype", "null"],
		togriJavob: 1,
	},
	{
		id: 172,
		bolim: "DOM bloki",
		mavzu: "Hodisalar (addEventListener)",
		savol: "Passive event listener ({ passive: true }) qanday afzallik beradi?",
		variantlar: [
			"Hodisani bir marta ishlatadi",
			"preventDefault() ga ruxsat bermaydi, brauzerga scroll animatsiyasini tezlashtirish imkonini beradi",
			"Hodisani capturing rejimida ishlatadi",
			"Hodisani asinxron boshqaradi",
		],
		togriJavob: 1,
	},
	{
		id: 173,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "window va location",
		savol: "window.confirm('Rostdan?') nima qaytaradi?",
		variantlar: ["String ('ok' yoki 'cancel')", "true (OK bossilsa) yoki false (Cancel bossilsa)", "Promise", "undefined"],
		togriJavob: 1,
	},
	{
		id: 174,
		bolim: "Asinxron JS bloki",
		mavzu: "Fetch API",
		savol: "AbortController fetch so'rovida qanday ishlatiladi?",
		variantlar: ["So'rovni tezlashtirish uchun", "Davom etayotgan fetch so'rovini bekor qilish (abort) uchun", "JSON parsing ni boshqarish uchun", "CORS ni o'chirish uchun"],
		togriJavob: 1,
	},
	{
		id: 175,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "RegEx",
		savol: "str.test(regex) ishlatilishi to'g'rimi?",
		variantlar: ["Ha, to'g'ri", "Yo'q — to'g'ri sintaksis: regex.test(str)", "Faqat Node.js da ishlaydi", "test() metodi mavjud emas"],
		togriJavob: 1,
	},
	{
		id: 176,
		bolim: "Funksiyalar va OOP",
		mavzu: "Metod Injection",
		savol: "call() va apply() metodlari o'rtasidagi farq nima?",
		variantlar: ["call() asinxron, apply() sinxron", "call() argumentlarni alohida, apply() esa massiv sifatida qabul qiladi", "apply() this ni o'zgartira olmaydi", "Hech qanday farq yo'q"],
		togriJavob: 1,
	},
	{
		id: 177,
		bolim: "DOM bloki",
		mavzu: "DOM Selektorlari",
		savol: "el.parentElement va el.parentNode farqi nima?",
		variantlar: ["Hech qanday farq yo'q", "parentElement faqat Element tugunini qaytaradi; parentNode istalgan tugun turini qaytaradi", "parentNode eskirgan", "parentElement tezroq"],
		togriJavob: 1,
	},
	{
		id: 178,
		bolim: "Asinxron JS bloki",
		mavzu: "Promise lar",
		savol: "Unhandled Promise Rejection nima?",
		variantlar: [
			"Promise pending holatida qolishi",
			"Rejected Promise uchun .catch() yoki try/catch bilan xato ushlashning yo'qligi",
			"Promise ning juda sekin ishlashi",
			"Promise ichida setTimeout ishlatilishi",
		],
		togriJavob: 1,
	},
	{
		id: 179,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "localStorage",
		savol: "localStorage uchun brauzer odatda qancha maksimal hajm ajratadi?",
		variantlar: ["1 KB", "100 KB", "~5 MB", "Cheksiz"],
		togriJavob: 2,
	},
	{
		id: 180,
		bolim: "Funksiyalar va OOP",
		mavzu: "Callback Funksiyalar",
		savol: "Node.js kabi muhitlarda error-first callback konventsiyasi nima?",
		variantlar: [
			"Callbackning birinchi parametri har doim xato (error) bo'ladi",
			"Callbackning oxirgi parametri xato bo'ladi",
			"Xato bo'lsa callback umuman chaqirilmaydi",
			"Error maxsus hodisa orqali uzatiladi",
		],
		togriJavob: 0,
	},
	{
		id: 181,
		bolim: "DOM bloki",
		mavzu: "Element Yaratish va O'chirish",
		savol: "el.cloneNode(true) nima qiladi?",
		variantlar: ["Elementni o'chiradi", "Elementni barcha farzandlari bilan birga chuqur nusxalaydi", "Faqat elementning o'zini (farzandlarsiz) nusxalaydi", "Elementni disable qiladi"],
		togriJavob: 1,
	},
	{
		id: 182,
		bolim: "Asinxron JS bloki",
		mavzu: "Async / Await",
		savol: "for await...of qanday holatlarda ishlatiladi?",
		variantlar: ["Oddiy massivlar uchun", "Asinxron iteratorlar (async generators, ReadableStream) bo'ylab aylanish uchun", "Promise.all o'rniga", "setTimeout zanjirini yaratish uchun"],
		togriJavob: 1,
	},
	{
		id: 183,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Stack va Heap",
		savol: "WeakMap va WeakSet nima uchun xotira boshqarishda afzal?",
		variantlar: [
			"Ular tezroq ishlaydi",
			"Kalitlari bo'yicha havola bo'lmasa, garbage collector ularni avtomatik tozalaydi (memory leak oldini oladi)",
			"Ular Map dan katta hajm saqlaydi",
			"Ular primitiv tiplarni ham saqlaydi",
		],
		togriJavob: 1,
	},
	{
		id: 184,
		bolim: "Funksiyalar va OOP",
		mavzu: "Class lar",
		savol: "instanceof operatori nima uchun ishlatiladi?",
		variantlar: [
			"Obyektning tipini string sifatida qaytaradi",
			"Obyektning prototip zanjiriga asoslanib u ma'lum klass ekzemplyari ekanini tekshiradi",
			"Ikki obyektni solishtiradi",
			"Klass metodlari sonini qaytaradi",
		],
		togriJavob: 1,
	},
	{
		id: 185,
		bolim: "DOM bloki",
		mavzu: "DOM Stil va Kontent O'zgartirish",
		savol: "el.getBoundingClientRect() nima qaytaradi?",
		variantlar: [
			"Elementning CSS stillarini",
			"Elementning viewport ga nisbatan koordinatalari va o'lchamlarini (top, left, width, height va h.k.)",
			"Elementning z-index qiymatini",
			"Elementning margin va padding qiymatlarini",
		],
		togriJavob: 1,
	},
	{
		id: 186,
		bolim: "Asinxron JS bloki",
		mavzu: "AJAX va API",
		savol: "HTTP PATCH va PUT metodlari o'rtasidagi farq nima?",
		variantlar: [
			"PATCH yangi resurs yaratadi, PUT eski resursni o'chiradi",
			"PUT resursni to'liq almashtiradi; PATCH faqat o'zgartirilgan maydonlarni yangilaydi",
			"PATCH tezroq ishlaydi",
			"Ular bir xil",
		],
		togriJavob: 1,
	},
	{
		id: 187,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Throw Errors",
		savol: "RangeError qachon yuz beradi?",
		variantlar: [
			"Mavjud bo'lmagan xususiyatga murojaat qilinganda",
			"Qiymat ruxsat etilgan diapazondan tashqarida bo'lganda (masalan, new Array(-1))",
			"Funksiya noto'g'ri chaqirilganda",
			"Sintaksis xatosi bo'lganda",
		],
		togriJavob: 1,
	},
	{
		id: 188,
		bolim: "Funksiyalar va OOP",
		mavzu: "High Order Functions",
		savol: "Array.prototype.some() va every() o'rtasidagi farq nima?",
		variantlar: [
			"Hech qanday farq yo'q",
			"some() hech bo'lmasa bitta element shartni qanoatlantirsa true; every() barcha elementlar qanoatlantirsa true",
			"every() hech bo'lmasa bittasi to'g'ri bo'lsa true",
			"some() birinchi elementni qaytaradi",
		],
		togriJavob: 1,
	},
	{
		id: 189,
		bolim: "DOM bloki",
		mavzu: "setAttribute / getAttribute",
		savol: "tabindex='0' atributi nima uchun ishlatiladi?",
		variantlar: [
			"Elementni yashirish uchun",
			"Elementni klaviatura orqali fokuslanishi (Tab bilan o'tish) mumkin qilish uchun",
			"Elementni birinchi o'ringa qo'yish uchun",
			"Z-index ni boshqarish uchun",
		],
		togriJavob: 1,
	},
	{
		id: 190,
		bolim: "BOM va Brauzer API-lari",
		mavzu: "new Date()",
		savol: "Intl.DateTimeFormat() nima uchun ishlatiladi?",
		variantlar: [
			"Sanani matematik hisoblash uchun",
			"Sanani turli tillar va mintaqalar formatida ko'rsatish uchun (internationalization)",
			"Sana va vaqtni solishtirish uchun",
			"Unix timestamp olish uchun",
		],
		togriJavob: 1,
	},
	{
		id: 191,
		bolim: "Asinxron JS bloki",
		mavzu: "Promise lar",
		savol: "Promise.any([p1, p2, p3]) nima qiladi?",
		variantlar: [
			"Barcha fulfilled promise larni qaytaradi",
			"Birinchi fulfilled promise ni qaytaradi; barchasi rejected bo'lsa AggregateError beradi",
			"Birinchi rejected promise ni qaytaradi",
			"Barcha promise larni kutadi",
		],
		togriJavob: 1,
	},
	{
		id: 192,
		bolim: "Funksiyalar va OOP",
		mavzu: "Closure",
		savol: "Module pattern nima va closure bilan qanday bog'liq?",
		variantlar: [
			"Bog'liqligi yo'q",
			"IIFE yoki funksiya ichida xususiy o'zgaruvchilar yaratib, faqat kerakli metodlarni expose qilish — closure ga asoslanadi",
			"Faqat ES6 modullari uchun",
			"Faqat class bilan ishlatiladi",
		],
		togriJavob: 1,
	},
	{
		id: 193,
		bolim: "DOM bloki",
		mavzu: "Hodisalar (addEventListener)",
		savol: "MutationObserver nima uchun ishlatiladi?",
		variantlar: [
			"DOM o'zgarishlarini (element qo'shish/o'chirish, atribut o'zgarishi) kuzatish uchun",
			"Mouse harakatlarini kuzatish uchun",
			"Tarmoq so'rovlarini kuzatish uchun",
			"LocalStorage o'zgarishlarini kuzatish uchun",
		],
		togriJavob: 0,
	},
	{
		id: 194,
		bolim: "Asinxron JS bloki",
		mavzu: "Fetch API",
		savol: "response.blob() nima uchun ishlatiladi?",
		variantlar: ["JSON ma'lumot olish uchun", "Ikkilik (binary) ma'lumot (rasm, fayl) olish uchun", "Matn ma'lumot olish uchun", "Sarlavhalar (headers) olish uchun"],
		togriJavob: 1,
	},
	{
		id: 195,
		bolim: "Xotira va Fundamental Tushunchalar",
		mavzu: "Deep Copy va Shallow Copy",
		savol: "Lodash _.cloneDeep(obj) nima qiladi?",
		variantlar: ["Shallow copy oladi", "Deep copy oladi (funksiyalar, Date, Map, Set kabi murakkab tiplarni ham to'g'ri nusxalaydi)", "Obyektni freeze qiladi", "Obyektni JSON ga o'giradi"],
		togriJavob: 1,
	},
	{
		id: 196,
		bolim: "Funksiyalar va OOP",
		mavzu: "Class lar",
		savol: "Object.freeze(obj) nima qiladi?",
		variantlar: [
			"Obyektni o'chiradi",
			"Obyektning xususiyatlarini o'zgartirib, yangi xususiyat qo'shib, o'chirib bo'lmaydigan qiladi",
			"Obyektni localStorage ga saqlaydi",
			"Obyektni deep copy qiladi",
		],
		togriJavob: 1,
	},
	{
		id: 197,
		bolim: "DOM bloki",
		mavzu: "DOM va BOM tushunchasi",
		savol: "Shadow DOM nima uchun ishlatiladi?",
		variantlar: ["Elementni sahifadan yashirish uchun", "Web Components uchun izolyatsiyalangan (encapsulated) DOM va CSS yaratish uchun", "DOM ni keshga saqlash uchun", "DOM ni tezlashtirish uchun"],
		togriJavob: 1,
	},
	{
		id: 198,
		bolim: "Asinxron JS bloki",
		mavzu: "Sinxron va Asinxron JS",
		savol: "queueMicrotask(fn) nima qiladi?",
		variantlar: [
			"fn ni setTimeout(fn, 0) kabi macrotask sifatida rejalashtiradi",
			"fn ni joriy skript tuggandan so'ng, DOM o'zgarishlari va boshqa macrotasklardan oldin microtask sifatida rejalashtiradi",
			"fn ni darhol sinxron bajaradi",
			"fn ni keyingi sahifa yuklashda bajaradi",
		],
		togriJavob: 1,
	},
	{
		id: 199,
		bolim: "Funksiyalar va OOP",
		mavzu: "High Order Functions",
		savol: "Currying (karrylash) nima?",
		variantlar: [
			"Funksiyani rekursiv chaqirish",
			"Ko'p argumentli funksiyani bitta argumentli funksiyalar zanjiriga aylantirish: f(a, b) → f(a)(b)",
			"Funksiyani keshga saqlash",
			"Callback zanjiri yaratish",
		],
		togriJavob: 1,
	},
	{
		id: 200,
		bolim: "Asinxron JS bloki",
		mavzu: "Fetch API",
		savol: "Fetch API yordamida fayl yuklab olishning to'g'ri usuli qaysi?",
		variantlar: [
			"fetch(url).download()",
			"response.blob() orqali Blob olinadi, keyin URL.createObjectURL() bilan yuklab olish linki yaratiladi",
			"fetch(url, { download: true })",
			"Fetch API fayl yuklab olishni qo'llab-quvvatlamaydi",
		],
		togriJavob: 1,
	},
];
